package librecon;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ASSISTANT_MEETING.
 */
public class AssistantMeeting {

    private Long id;
    private Long assistantId;
    private Long meetingId;

    public AssistantMeeting() {
    }

    public AssistantMeeting(Long id) {
        this.id = id;
    }

    public AssistantMeeting(Long id, Long assistantId, Long meetingId) {
        this.id = id;
        this.assistantId = assistantId;
        this.meetingId = meetingId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAssistantId() {
        return assistantId;
    }

    public void setAssistantId(Long assistantId) {
        this.assistantId = assistantId;
    }

    public Long getMeetingId() {
        return meetingId;
    }

    public void setMeetingId(Long meetingId) {
        this.meetingId = meetingId;
    }

}
