package librecon;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import librecon.Assistant;
import librecon.Speaker;
import librecon.Schedule;
import librecon.ScheduleSpeaker;
import librecon.Tag;
import librecon.Sponsor;
import librecon.Expositor;
import librecon.Txoko;
import librecon.LastModified;
import librecon.Me;
import librecon.Meeting;
import librecon.AssistantMeeting;

import librecon.AssistantDao;
import librecon.SpeakerDao;
import librecon.ScheduleDao;
import librecon.ScheduleSpeakerDao;
import librecon.TagDao;
import librecon.SponsorDao;
import librecon.ExpositorDao;
import librecon.TxokoDao;
import librecon.LastModifiedDao;
import librecon.MeDao;
import librecon.MeetingDao;
import librecon.AssistantMeetingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig assistantDaoConfig;
    private final DaoConfig speakerDaoConfig;
    private final DaoConfig scheduleDaoConfig;
    private final DaoConfig scheduleSpeakerDaoConfig;
    private final DaoConfig tagDaoConfig;
    private final DaoConfig sponsorDaoConfig;
    private final DaoConfig expositorDaoConfig;
    private final DaoConfig txokoDaoConfig;
    private final DaoConfig lastModifiedDaoConfig;
    private final DaoConfig meDaoConfig;
    private final DaoConfig meetingDaoConfig;
    private final DaoConfig assistantMeetingDaoConfig;

    private final AssistantDao assistantDao;
    private final SpeakerDao speakerDao;
    private final ScheduleDao scheduleDao;
    private final ScheduleSpeakerDao scheduleSpeakerDao;
    private final TagDao tagDao;
    private final SponsorDao sponsorDao;
    private final ExpositorDao expositorDao;
    private final TxokoDao txokoDao;
    private final LastModifiedDao lastModifiedDao;
    private final MeDao meDao;
    private final MeetingDao meetingDao;
    private final AssistantMeetingDao assistantMeetingDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        assistantDaoConfig = daoConfigMap.get(AssistantDao.class).clone();
        assistantDaoConfig.initIdentityScope(type);

        speakerDaoConfig = daoConfigMap.get(SpeakerDao.class).clone();
        speakerDaoConfig.initIdentityScope(type);

        scheduleDaoConfig = daoConfigMap.get(ScheduleDao.class).clone();
        scheduleDaoConfig.initIdentityScope(type);

        scheduleSpeakerDaoConfig = daoConfigMap.get(ScheduleSpeakerDao.class).clone();
        scheduleSpeakerDaoConfig.initIdentityScope(type);

        tagDaoConfig = daoConfigMap.get(TagDao.class).clone();
        tagDaoConfig.initIdentityScope(type);

        sponsorDaoConfig = daoConfigMap.get(SponsorDao.class).clone();
        sponsorDaoConfig.initIdentityScope(type);

        expositorDaoConfig = daoConfigMap.get(ExpositorDao.class).clone();
        expositorDaoConfig.initIdentityScope(type);

        txokoDaoConfig = daoConfigMap.get(TxokoDao.class).clone();
        txokoDaoConfig.initIdentityScope(type);

        lastModifiedDaoConfig = daoConfigMap.get(LastModifiedDao.class).clone();
        lastModifiedDaoConfig.initIdentityScope(type);

        meDaoConfig = daoConfigMap.get(MeDao.class).clone();
        meDaoConfig.initIdentityScope(type);

        meetingDaoConfig = daoConfigMap.get(MeetingDao.class).clone();
        meetingDaoConfig.initIdentityScope(type);

        assistantMeetingDaoConfig = daoConfigMap.get(AssistantMeetingDao.class).clone();
        assistantMeetingDaoConfig.initIdentityScope(type);

        assistantDao = new AssistantDao(assistantDaoConfig, this);
        speakerDao = new SpeakerDao(speakerDaoConfig, this);
        scheduleDao = new ScheduleDao(scheduleDaoConfig, this);
        scheduleSpeakerDao = new ScheduleSpeakerDao(scheduleSpeakerDaoConfig, this);
        tagDao = new TagDao(tagDaoConfig, this);
        sponsorDao = new SponsorDao(sponsorDaoConfig, this);
        expositorDao = new ExpositorDao(expositorDaoConfig, this);
        txokoDao = new TxokoDao(txokoDaoConfig, this);
        lastModifiedDao = new LastModifiedDao(lastModifiedDaoConfig, this);
        meDao = new MeDao(meDaoConfig, this);
        meetingDao = new MeetingDao(meetingDaoConfig, this);
        assistantMeetingDao = new AssistantMeetingDao(assistantMeetingDaoConfig, this);

        registerDao(Assistant.class, assistantDao);
        registerDao(Speaker.class, speakerDao);
        registerDao(Schedule.class, scheduleDao);
        registerDao(ScheduleSpeaker.class, scheduleSpeakerDao);
        registerDao(Tag.class, tagDao);
        registerDao(Sponsor.class, sponsorDao);
        registerDao(Expositor.class, expositorDao);
        registerDao(Txoko.class, txokoDao);
        registerDao(LastModified.class, lastModifiedDao);
        registerDao(Me.class, meDao);
        registerDao(Meeting.class, meetingDao);
        registerDao(AssistantMeeting.class, assistantMeetingDao);
    }
    
    public void clear() {
        assistantDaoConfig.getIdentityScope().clear();
        speakerDaoConfig.getIdentityScope().clear();
        scheduleDaoConfig.getIdentityScope().clear();
        scheduleSpeakerDaoConfig.getIdentityScope().clear();
        tagDaoConfig.getIdentityScope().clear();
        sponsorDaoConfig.getIdentityScope().clear();
        expositorDaoConfig.getIdentityScope().clear();
        txokoDaoConfig.getIdentityScope().clear();
        lastModifiedDaoConfig.getIdentityScope().clear();
        meDaoConfig.getIdentityScope().clear();
        meetingDaoConfig.getIdentityScope().clear();
        assistantMeetingDaoConfig.getIdentityScope().clear();
    }

    public AssistantDao getAssistantDao() {
        return assistantDao;
    }

    public SpeakerDao getSpeakerDao() {
        return speakerDao;
    }

    public ScheduleDao getScheduleDao() {
        return scheduleDao;
    }

    public ScheduleSpeakerDao getScheduleSpeakerDao() {
        return scheduleSpeakerDao;
    }

    public TagDao getTagDao() {
        return tagDao;
    }

    public SponsorDao getSponsorDao() {
        return sponsorDao;
    }

    public ExpositorDao getExpositorDao() {
        return expositorDao;
    }

    public TxokoDao getTxokoDao() {
        return txokoDao;
    }

    public LastModifiedDao getLastModifiedDao() {
        return lastModifiedDao;
    }

    public MeDao getMeDao() {
        return meDao;
    }

    public MeetingDao getMeetingDao() {
        return meetingDao;
    }

    public AssistantMeetingDao getAssistantMeetingDao() {
        return assistantMeetingDao;
    }

}
