package librecon;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

import java.util.Locale;

/**
 * Entity mapped to table EXPOSITOR.
 */
public class Expositor implements Parcelable {

    private Long id;
    private String descriptionEs;
    private String descriptionEu;
    private String descriptionEn;
    private String company;
    private String picUrl;
    private String url;
    private Integer orderField;

    public Expositor() {
    }

    public Expositor(Long id) {
        this.id = id;
    }

    public Expositor(Long id, String descriptionEs, String descriptionEu, String descriptionEn, String company, String picUrl, String url, Integer orderField) {
        this.id = id;
        this.descriptionEs = descriptionEs;
        this.descriptionEu = descriptionEu;
        this.descriptionEn = descriptionEn;
        this.company = company;
        this.picUrl = picUrl;
        this.url = url;
        this.orderField = orderField;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescriptionEs() {
        return descriptionEs;
    }

    public void setDescriptionEs(String descriptionEs) {
        this.descriptionEs = descriptionEs;
    }

    public String getDescriptionEu() {
        return descriptionEu;
    }

    public void setDescriptionEu(String descriptionEu) {
        this.descriptionEu = descriptionEu;
    }

    public String getDescriptionEn() {
        return descriptionEn;
    }

    public void setDescriptionEn(String descriptionEn) {
        this.descriptionEn = descriptionEn;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getPicUrl() {
        return picUrl;
    }

    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getOrderField() {
        return orderField;
    }

    public void setOrderField(Integer orderField) {
        this.orderField = orderField;
    }

    public String getDescription() {
        Locale locale = Locale.getDefault();
        String language = locale.getLanguage();
        if (language.equals("eu")) {
            return this.descriptionEu;
        } else if (language.equals("en")) {
            return this.descriptionEn;
        } else {
            return this.descriptionEs;
        }
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.descriptionEs);
        dest.writeString(this.descriptionEu);
        dest.writeString(this.descriptionEn);
        dest.writeString(this.company);
        dest.writeString(this.picUrl);
        dest.writeString(this.url);
        dest.writeValue(this.orderField);
    }

    private Expositor(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.descriptionEs = in.readString();
        this.descriptionEu = in.readString();
        this.descriptionEn = in.readString();
        this.company = in.readString();
        this.picUrl = in.readString();
        this.url = in.readString();
        this.orderField = (Integer) in.readValue(Integer.class.getClassLoader());
    }

    public static final Creator<Expositor> CREATOR = new Creator<Expositor>() {
        public Expositor createFromParcel(Parcel source) {
            return new Expositor(source);
        }

        public Expositor[] newArray(int size) {
            return new Expositor[size];
        }
    };
}
