package librecon;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import librecon.Expositor;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table EXPOSITOR.
*/
public class ExpositorDao extends AbstractDao<Expositor, Long> {

    public static final String TABLENAME = "EXPOSITOR";

    /**
     * Properties of entity Expositor.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DescriptionEs = new Property(1, String.class, "descriptionEs", false, "DESCRIPTION_ES");
        public final static Property DescriptionEu = new Property(2, String.class, "descriptionEu", false, "DESCRIPTION_EU");
        public final static Property DescriptionEn = new Property(3, String.class, "descriptionEn", false, "DESCRIPTION_EN");
        public final static Property Company = new Property(4, String.class, "company", false, "COMPANY");
        public final static Property PicUrl = new Property(5, String.class, "picUrl", false, "PIC_URL");
        public final static Property Url = new Property(6, String.class, "url", false, "URL");
        public final static Property OrderField = new Property(7, Integer.class, "orderField", false, "ORDER_FIELD");
    };


    public ExpositorDao(DaoConfig config) {
        super(config);
    }
    
    public ExpositorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'EXPOSITOR' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'DESCRIPTION_ES' TEXT," + // 1: descriptionEs
                "'DESCRIPTION_EU' TEXT," + // 2: descriptionEu
                "'DESCRIPTION_EN' TEXT," + // 3: descriptionEn
                "'COMPANY' TEXT," + // 4: company
                "'PIC_URL' TEXT," + // 5: picUrl
                "'URL' TEXT," + // 6: url
                "'ORDER_FIELD' INTEGER);"); // 7: orderField
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'EXPOSITOR'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Expositor entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String descriptionEs = entity.getDescriptionEs();
        if (descriptionEs != null) {
            stmt.bindString(2, descriptionEs);
        }
 
        String descriptionEu = entity.getDescriptionEu();
        if (descriptionEu != null) {
            stmt.bindString(3, descriptionEu);
        }
 
        String descriptionEn = entity.getDescriptionEn();
        if (descriptionEn != null) {
            stmt.bindString(4, descriptionEn);
        }
 
        String company = entity.getCompany();
        if (company != null) {
            stmt.bindString(5, company);
        }
 
        String picUrl = entity.getPicUrl();
        if (picUrl != null) {
            stmt.bindString(6, picUrl);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(7, url);
        }
 
        Integer orderField = entity.getOrderField();
        if (orderField != null) {
            stmt.bindLong(8, orderField);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Expositor readEntity(Cursor cursor, int offset) {
        Expositor entity = new Expositor( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // descriptionEs
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // descriptionEu
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // descriptionEn
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // company
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // picUrl
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // url
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7) // orderField
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Expositor entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDescriptionEs(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDescriptionEu(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDescriptionEn(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCompany(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPicUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setUrl(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setOrderField(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Expositor entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Expositor entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
