package librecon;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table MEETING.
 */
public class Meeting implements Parcelable {

    private Long id;
    private Boolean sendedByMe;
    private String createdAt;
    private Integer status;
    private Boolean emailShare;
    private Boolean cellphoneShare;
    private String moment;
    private String responseDate;

    public Meeting() {
    }

    public Meeting(Long id) {
        this.id = id;
    }

    public Meeting(Long id, Boolean sendedByMe, String createdAt, Integer status, Boolean emailShare, Boolean cellphoneShare, String moment, String responseDate) {
        this.id = id;
        this.sendedByMe = sendedByMe;
        this.createdAt = createdAt;
        this.status = status;
        this.emailShare = emailShare;
        this.cellphoneShare = cellphoneShare;
        this.moment = moment;
        this.responseDate = responseDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getSendedByMe() {
        return sendedByMe;
    }

    public void setSendedByMe(Boolean sendedByMe) {
        this.sendedByMe = sendedByMe;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Boolean getEmailShare() {
        return emailShare;
    }

    public void setEmailShare(Boolean emailShare) {
        this.emailShare = emailShare;
    }

    public Boolean getCellphoneShare() {
        return cellphoneShare;
    }

    public void setCellphoneShare(Boolean cellphoneShare) {
        this.cellphoneShare = cellphoneShare;
    }

    public String getMoment() {
        return moment;
    }

    public void setMoment(String moment) {
        this.moment = moment;
    }

    public String getResponseDate() {
        return responseDate;
    }

    public void setResponseDate(String responseDate) {
        this.responseDate = responseDate;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeValue(this.sendedByMe);
        dest.writeString(this.createdAt);
        dest.writeValue(this.status);
        dest.writeValue(this.emailShare);
        dest.writeValue(this.cellphoneShare);
        dest.writeString(this.moment);
        dest.writeString(this.responseDate);
    }

    private Meeting(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.sendedByMe = (Boolean) in.readValue(Boolean.class.getClassLoader());
        this.createdAt = in.readString();
        this.status = (Integer) in.readValue(Integer.class.getClassLoader());
        this.emailShare = (Boolean) in.readValue(Boolean.class.getClassLoader());
        this.cellphoneShare = (Boolean) in.readValue(Boolean.class.getClassLoader());
        this.moment = in.readString();
        this.responseDate = in.readString();
    }

    public static final Creator<Meeting> CREATOR = new Creator<Meeting>() {
        public Meeting createFromParcel(Parcel source) {
            return new Meeting(source);
        }

        public Meeting[] newArray(int size) {
            return new Meeting[size];
        }
    };
}
