package librecon;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SCHEDULE_SPEAKER.
 */
public class ScheduleSpeaker {

    private Long id;
    private Long speakerId;
    private Long scheduleId;

    public ScheduleSpeaker() {
    }

    public ScheduleSpeaker(Long id) {
        this.id = id;
    }

    public ScheduleSpeaker(Long id, Long speakerId, Long scheduleId) {
        this.id = id;
        this.speakerId = speakerId;
        this.scheduleId = scheduleId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSpeakerId() {
        return speakerId;
    }

    public void setSpeakerId(Long speakerId) {
        this.speakerId = speakerId;
    }

    public Long getScheduleId() {
        return scheduleId;
    }

    public void setScheduleId(Long scheduleId) {
        this.scheduleId = scheduleId;
    }

}
