ALTER TABLE `Expositor` ADD `description_es` mediumtext NOT NULL  COMMENT '' AFTER `description`;
ALTER TABLE `Expositor` ADD `description_en` mediumtext NOT NULL  COMMENT '' AFTER `description`;
ALTER TABLE `Expositor` ADD `description_eu` mediumtext NOT NULL  COMMENT '' AFTER `description`;
ALTER TABLE `Expositor` ADD `logoBaseName` VARCHAR(255) NOT NULL  COMMENT '' AFTER `logo`;
ALTER TABLE `Expositor` ADD `logoMimeType` VARCHAR(80) NOT NULL  COMMENT '' AFTER `logo`;
ALTER TABLE `Expositor` ADD `logoFileSize` INT(11) UNSIGNED NOT NULL  COMMENT '[FSO]' AFTER `logo`;
ALTER TABLE `Expositor` DROP logo;
ALTER TABLE `Schedule` ADD `name_es` varchar(255) NOT NULL  COMMENT '' AFTER `name`;
ALTER TABLE `Schedule` ADD `name_en` varchar(255) NOT NULL  COMMENT '' AFTER `name`;
ALTER TABLE `Schedule` ADD `name_eu` varchar(255) NOT NULL  COMMENT '' AFTER `name`;
ALTER TABLE `Schedule` ADD `description_es` mediumtext COMMENT '[html]' AFTER `description`;
ALTER TABLE `Schedule` ADD `description_en` mediumtext COMMENT '[html]' AFTER `description`;
ALTER TABLE `Schedule` ADD `description_eu` mediumtext COMMENT '[html]' AFTER `description`;
ALTER TABLE `Schedule` ADD `pictureBaseName` VARCHAR(255) COMMENT '' AFTER `picture`;
ALTER TABLE `Schedule` ADD `pictureMimeType` VARCHAR(80) COMMENT '' AFTER `picture`;
ALTER TABLE `Schedule` ADD `pictureFileSize` INT(11) UNSIGNED COMMENT '[FSO]' AFTER `picture`;
ALTER TABLE `Schedule` DROP picture;
ALTER TABLE `Speaker` ADD `description_es` mediumtext COMMENT '' AFTER `description`;
ALTER TABLE `Speaker` ADD `description_en` mediumtext COMMENT '' AFTER `description`;
ALTER TABLE `Speaker` ADD `description_eu` mediumtext COMMENT '' AFTER `description`;
ALTER TABLE `Speaker` ADD `pictureBaseName` VARCHAR(255) COMMENT '' AFTER `picture`;
ALTER TABLE `Speaker` ADD `pictureMimeType` VARCHAR(80) COMMENT '' AFTER `picture`;
ALTER TABLE `Speaker` ADD `pictureFileSize` INT(11) UNSIGNED COMMENT '[FSO]' AFTER `picture`;
ALTER TABLE `Speaker` DROP picture;
ALTER TABLE `Sponsors` ADD `name_es` varchar(255) NOT NULL  COMMENT '' AFTER `name`;
ALTER TABLE `Sponsors` ADD `name_en` varchar(255) NOT NULL  COMMENT '' AFTER `name`;
ALTER TABLE `Sponsors` ADD `name_eu` varchar(255) NOT NULL  COMMENT '' AFTER `name`;
ALTER TABLE `Tags` ADD `name_es` varchar(255) NOT NULL  COMMENT '' AFTER `name`;
ALTER TABLE `Tags` ADD `name_en` varchar(255) NOT NULL  COMMENT '' AFTER `name`;
ALTER TABLE `Tags` ADD `name_eu` varchar(255) NOT NULL  COMMENT '' AFTER `name`;
ALTER TABLE `Txoko` ADD `title_es` varchar(255) NOT NULL  COMMENT '' AFTER `title`;
ALTER TABLE `Txoko` ADD `title_en` varchar(255) NOT NULL  COMMENT '' AFTER `title`;
ALTER TABLE `Txoko` ADD `title_eu` varchar(255) NOT NULL  COMMENT '' AFTER `title`;
ALTER TABLE `Txoko` ADD `text_es` mediumtext COMMENT '' AFTER `text`;
ALTER TABLE `Txoko` ADD `text_en` mediumtext COMMENT '' AFTER `text`;
ALTER TABLE `Txoko` ADD `text_eu` mediumtext COMMENT '' AFTER `text`;
ALTER TABLE `Txoko` ADD `pictureBaseName` VARCHAR(255) COMMENT '' AFTER `picture`;
ALTER TABLE `Txoko` ADD `pictureMimeType` VARCHAR(80) COMMENT '' AFTER `picture`;
ALTER TABLE `Txoko` ADD `pictureFileSize` INT(11) UNSIGNED COMMENT '[FSO]' AFTER `picture`;
ALTER TABLE `Txoko` DROP picture;
