ALTER TABLE `Sponsors` ADD `link1` VARCHAR(255) NULL DEFAULT NULL , ADD `link1Type` MEDIUMINT(8) UNSIGNED NULL DEFAULT NULL , ADD `link2` VARCHAR(255) NULL DEFAULT NULL , ADD `link2Type` MEDIUMINT(8) UNSIGNED NULL DEFAULT NULL , ADD `link3` VARCHAR(255) NULL DEFAULT NULL , ADD `link3Type` MEDIUMINT(8) UNSIGNED NULL DEFAULT NULL , ADD `link4` VARCHAR(255) NULL DEFAULT NULL , ADD `link4Type` MEDIUMINT(8) UNSIGNED NULL DEFAULT NULL ;

ALTER TABLE `Sponsors` ADD INDEX(`link1Type`);

ALTER TABLE `Sponsors` ADD INDEX(`link2Type`);

ALTER TABLE `Sponsors` ADD INDEX(`link3Type`);

ALTER TABLE `Sponsors` ADD INDEX(`link4Type`);

ALTER TABLE `Sponsors` ADD FOREIGN KEY (`link1Type`) REFERENCES `Links`(`id`) ON DELETE SET NULL ON UPDATE SET NULL; 
ALTER TABLE `Sponsors` ADD FOREIGN KEY (`link2Type`) REFERENCES `Links`(`id`) ON DELETE SET NULL ON UPDATE SET NULL; 
ALTER TABLE `Sponsors` ADD FOREIGN KEY (`link3Type`) REFERENCES `Links`(`id`) ON DELETE SET NULL ON UPDATE SET NULL; 
ALTER TABLE `Sponsors` ADD FOREIGN KEY (`link4Type`) REFERENCES `Links`(`id`) ON DELETE SET NULL ON UPDATE SET NULL;

-- ALTER TABLE `Schedule` ADD FOREIGN KEY (`link1Type`) REFERENCES `Links`(`id`) ON DELETE SET NULL ON UPDATE SET NULL; 
-- ALTER TABLE `Schedule` ADD FOREIGN KEY (`link2Type`) REFERENCES `Links`(`id`) ON DELETE SET NULL ON UPDATE SET NULL; 
-- ALTER TABLE `Schedule` ADD FOREIGN KEY (`link3Type`) REFERENCES `Links`(`id`) ON DELETE SET NULL ON UPDATE SET NULL; 
-- ALTER TABLE `Schedule` ADD FOREIGN KEY (`link4Type`) REFERENCES `Links`(`id`) ON DELETE SET NULL ON UPDATE SET NULL;