ALTER TABLE `Speaker` ADD `link1` VARCHAR(255) NULL DEFAULT NULL , ADD `link1Type` MEDIUMINT(8) UNSIGNED NULL DEFAULT NULL , ADD `link2` VARCHAR(255) NULL DEFAULT NULL , ADD `link2Type` MEDIUMINT(8) UNSIGNED NULL DEFAULT NULL , ADD `link3` VARCHAR(255) NULL DEFAULT NULL , ADD `link3Type` MEDIUMINT(8) UNSIGNED NULL DEFAULT NULL , ADD `link4` VARCHAR(255) NULL DEFAULT NULL , ADD `link4Type` MEDIUMINT(8) UNSIGNED NULL DEFAULT NULL ;

ALTER TABLE `Speaker` ADD INDEX(`link1Type`);

ALTER TABLE `Speaker` ADD INDEX(`link2Type`);

ALTER TABLE `Speaker` ADD INDEX(`link3Type`);

ALTER TABLE `Speaker` ADD INDEX(`link4Type`);

ALTER TABLE `Speaker` ADD FOREIGN KEY (`link1Type`) REFERENCES `Links`(`id`) ON DELETE SET NULL ON UPDATE SET NULL; 
ALTER TABLE `Speaker` ADD FOREIGN KEY (`link2Type`) REFERENCES `Links`(`id`) ON DELETE SET NULL ON UPDATE SET NULL; 
ALTER TABLE `Speaker` ADD FOREIGN KEY (`link3Type`) REFERENCES `Links`(`id`) ON DELETE SET NULL ON UPDATE SET NULL; 
ALTER TABLE `Speaker` ADD FOREIGN KEY (`link4Type`) REFERENCES `Links`(`id`) ON DELETE SET NULL ON UPDATE SET NULL;

ALTER TABLE `Sponsors` DROP FOREIGN KEY `Sponsors_ibfk_1`; ALTER TABLE `Sponsors` DROP FOREIGN KEY `Sponsors_ibfk_2`; ALTER TABLE `Sponsors` DROP FOREIGN KEY `Sponsors_ibfk_3`; ALTER TABLE `Sponsors` DROP FOREIGN KEY `Sponsors_ibfk_4`;

ALTER TABLE `Sponsors` DROP `link1`, DROP `link1Type`, DROP `link2`, DROP `link2Type`, DROP `link3`, DROP `link3Type`, DROP `link4`, DROP `link4Type`;