INSERT INTO `KlearSections` (`id`, `name`, `description`, `identifier`) VALUES ('1', 'AssistantsList', 'AssistantsList', 'AssistantsList');
INSERT INTO `KlearSections` (`id`, `name`, `description`, `identifier`) VALUES ('2', 'ExpositorList', 'ExpositorList', 'ExpositorList');
INSERT INTO `KlearSections` (`id`, `name`, `description`, `identifier`) VALUES ('3', 'KlearRolesList', 'KlearRolesList', 'KlearRolesList');
INSERT INTO `KlearSections` (`id`, `name`, `description`, `identifier`) VALUES ('4', 'KlearRolesSectionsList', 'KlearRolesSectionsList', 'KlearRolesSectionsList');
INSERT INTO `KlearSections` (`id`, `name`, `description`, `identifier`) VALUES ('5', 'KlearUsersList', 'KlearUsersList', 'KlearUsersList');
INSERT INTO `KlearSections` (`id`, `name`, `description`, `identifier`) VALUES ('6', 'KlearUsersRolesList', 'KlearUsersRolesList', 'KlearUsersRolesList');
INSERT INTO `KlearSections` (`id`, `name`, `description`, `identifier`) VALUES ('7', 'LinksList', 'LinksList', 'LinksList');
INSERT INTO `KlearSections` (`id`, `name`, `description`, `identifier`) VALUES ('8', 'MeetingList', 'MeetingList', 'MeetingList');
INSERT INTO `KlearSections` (`id`, `name`, `description`, `identifier`) VALUES ('9', 'RelScheduleSpeakerList', 'RelScheduleSpeakerList', 'RelScheduleSpeakerList');
INSERT INTO `KlearSections` (`id`, `name`, `description`, `identifier`) VALUES ('10', 'RelTagSchedueleList', 'RelTagSchedueleList', 'RelTagSchedueleList');
INSERT INTO `KlearSections` (`id`, `name`, `description`, `identifier`) VALUES ('11', 'RelTagSpeakerList', 'RelTagSpeakerList', 'RelTagSpeakerList');
INSERT INTO `KlearSections` (`id`, `name`, `description`, `identifier`) VALUES ('12', 'ScheduleList', 'ScheduleList', 'ScheduleList');
INSERT INTO `KlearSections` (`id`, `name`, `description`, `identifier`) VALUES ('13', 'SpeakerList', 'SpeakerList', 'SpeakerList');
INSERT INTO `KlearSections` (`id`, `name`, `description`, `identifier`) VALUES ('14', 'SponsorsList', 'SponsorsList', 'SponsorsList');
INSERT INTO `KlearSections` (`id`, `name`, `description`, `identifier`) VALUES ('15', 'TagsList', 'TagsList', 'TagsList');
INSERT INTO `KlearSections` (`id`, `name`, `description`, `identifier`) VALUES ('16', 'TxokoList', 'TxokoList', 'TxokoList');
INSERT INTO `KlearSections` (`id`, `name`, `description`, `identifier`) VALUES ('17', 'VersionsList', 'VersionsList', 'VersionsList');

INSERT INTO `KlearRolesSections` (`id`, `klearRoleId`, `klearSectionId`) VALUES ('1', '1', '1');
INSERT INTO `KlearRolesSections` (`id`, `klearRoleId`, `klearSectionId`) VALUES ('2', '1', '2');
INSERT INTO `KlearRolesSections` (`id`, `klearRoleId`, `klearSectionId`) VALUES ('3', '1', '3');
INSERT INTO `KlearRolesSections` (`id`, `klearRoleId`, `klearSectionId`) VALUES ('4', '1', '4');
INSERT INTO `KlearRolesSections` (`id`, `klearRoleId`, `klearSectionId`) VALUES ('5', '1', '5');
INSERT INTO `KlearRolesSections` (`id`, `klearRoleId`, `klearSectionId`) VALUES ('6', '1', '6');
INSERT INTO `KlearRolesSections` (`id`, `klearRoleId`, `klearSectionId`) VALUES ('7', '1', '7');
INSERT INTO `KlearRolesSections` (`id`, `klearRoleId`, `klearSectionId`) VALUES ('8', '1', '8');
INSERT INTO `KlearRolesSections` (`id`, `klearRoleId`, `klearSectionId`) VALUES ('9', '1', '9');
INSERT INTO `KlearRolesSections` (`id`, `klearRoleId`, `klearSectionId`) VALUES ('10', '1', '10');
INSERT INTO `KlearRolesSections` (`id`, `klearRoleId`, `klearSectionId`) VALUES ('11', '1', '11');
INSERT INTO `KlearRolesSections` (`id`, `klearRoleId`, `klearSectionId`) VALUES ('12', '1', '12');
INSERT INTO `KlearRolesSections` (`id`, `klearRoleId`, `klearSectionId`) VALUES ('13', '1', '13');
INSERT INTO `KlearRolesSections` (`id`, `klearRoleId`, `klearSectionId`) VALUES ('14', '1', '14');
INSERT INTO `KlearRolesSections` (`id`, `klearRoleId`, `klearSectionId`) VALUES ('15', '1', '15');
INSERT INTO `KlearRolesSections` (`id`, `klearRoleId`, `klearSectionId`) VALUES ('16', '1', '16');
INSERT INTO `KlearRolesSections` (`id`, `klearRoleId`, `klearSectionId`) VALUES ('17', '1', '17');